---
- name: homework25 provision
  hosts: inetRouter
  become: true
  tasks:
  - name: install iptables
    yum:
      name:
        - iptables
        - iptables-services
      state: present
      update_cache: true
  - name: copy iptables config
    template:
      src: iptables-InetRouter
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0600
  - name: start and enable iptables service
    service:
      name: iptables
      state: restarted
      enabled: true
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
      
- hosts: centralRouter, office1router, office2router
  become: true
  tasks:
  - name: install iptables
    yum:
      name:
        - iptables
        - iptables-services
      state: present
      update_cache: true
  - name: copy iptables config
    template:
      src: iptables-Router
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0600
  - name: start and enable iptables service
    service:
      name: iptables
      state: restarted
      enabled: true
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

- hosts: inetRouter
  become: true
  tasks:
  - name: add route to internal network
    lineinfile:
      dest: /etc/sysconfig/network-scripts/route-eth1
      line: 192.168.0.0/16 via 192.168.255.2 
      create: true
     
- hosts: centralRouter 
  become: true
  tasks:
  - name: deisable default route centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.255.1
      - DEFROUTE=yes
      
  - name: add route to internal network off1
    lineinfile:
      dest: /etc/sysconfig/network-scripts/route-eth5
      line: "{{ item }}" 
      create: true
    loop:
      - 192.168.2.0/26 via 192.168.255.6 
      - 192.168.2.64/26 via 192.168.255.6
      - 192.168.2.128/26 via 192.168.255.6
      - 192.168.2.192/26 via 192.168.255.6
      
  - name: add route to internal network off2
    lineinfile:
      dest: /etc/sysconfig/network-scripts/route-eth6
      line: "{{ item }}" 
      create: true
    loop:
      - 192.168.1.0/25 via 192.168.255.10 
      - 192.168.1.128/26 via 192.168.255.10
      - 192.168.1.192/26 via 192.168.255.10

- hosts: office1router 
  become: true
  tasks:
  - name: deisable default route centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.255.5
      - DEFROUTE=yes
      
- hosts: office2router 
  become: true
  tasks:
  - name: deisable default route centralRouter
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.255.9
      - DEFROUTE=yes

- hosts: centralServer
  become: true
  tasks:
  - name: deisable default route centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.0.1
      - DEFROUTE=yes 
      
- hosts: office1Server
  become: true
  tasks:
  - name: deisable default route centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.2.193
      - DEFROUTE=yes

- hosts: office2Server
  become: true
  tasks:
  - name: deisable default route centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.1.193
      - DEFROUTE=yes
 
- hosts: inetRouter, centralRouter, office1router, office2router, centralServer, office1Server, office2Server
  become: true
  tasks:
  - name: restart network 01
    service:
      name: network
      state: restarted
  - name: restart network 02
    service:
      name: network
      state: restarted
      
 
