---
- hosts: inetRouter, centralRouter
  become: true
  tasks:
  - name: install iptables
    yum:
      name:
        - iptables
        - iptables-services
      state: present
      update_cache: true
  - name: copy iptables config
    template:
      src: iptables-inetRouter
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0600
  - name: start and enable iptables service
    service:
      name: iptables
      state: restarted
      enabled: true
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
   
- hosts: centralServer
  become: true
  tasks:
  - name: deisable default route centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.0.1
      - DEFROUTE=yes
      
- hosts: centralRouter 
  become: true
  tasks:
  - name: deisable default route centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "{{ item }}" 
    loop:
      - GATEWAY=192.168.255.1
      - DEFROUTE=yes     
